### ISSUE TITLE
¿Qué frameworks usáis?

### ISSUE THREAD

**Issue by juanmirod** [Frontaneria/Open-Support#5]
Una pregunta para romper el hielo :smile: ¿Qué frameworks usáis en la Frontanería? Tanto JS como CSS,  Angular(+RxJS?), Vue, React(+Redux?), jQuery, Sass, Less, Bootstrap, Foundation, Polymer, Material.... La lista es larga, no pretendo empezar una discusión sobre cuál es mejor, cada uno tendrá sus preferencias y cada proyecto encaja mejor con uno u otro. Solo es por tener una idea de qué estáis usando y sobre que temas se puede preguntar.

**Comment by aarongarciah** [comment]
¡Hola @juanmirod!

- **Javascript**: no uso jQuery, salvo que entre a un proyecto que esté metido y no se pueda quitar.
- **Framework Javascript**: uso **React**. Personalmente me encanta trabajar con el estado de React, por ello no meto **Redux** en el proyecto salvo que lo vea necesario. He tocado poquísimo Angular y de Vue conozco lo que he visto/leído en unos cuantos tutoriales. Me encantó aprender React ya que me obligó a aprender correctamente conceptos de JavaScript que hasta ese momento no tenía bien interiorizados. Me gustaría profundizar en Vue a medio plazo.
- **CSS**: uso **Sass + Autoprefixer (PostCSS)** para el CSS. En ocasiones uso únicamente PostCSS pero sólo los plugins cssNext, Autoprefixer, postcss-imports y postcss-mixins.
- **Framework CSS**: No uso framework CSS salvo que entre a un proyecto que ya esté usando uno y sea imperativo usarlo.
- **CSS en React**: lo que mas he usado es CSS Modules, pero en los proyectos nuevos tengo claro que voy a usar **[styled-components](https://www.styled-components.com/)**.

**Comment by gimenete** [comment]
- React o Vue.js. Siempre me ha gustado más Vue.js, pero normalmente me "imponen" React
- TypeScript si puedo
- SCSS o CSS a pelo
- Blueprint http://blueprintjs.com si tengo que hacer una aplicación desktop-like

**Comment by IgnaciodeNuevo** [comment]
- **JavaScript** vanilla
- CSS: Uso **Sass + Autoprefixer** pero pasaré a **PostCSS** cuando acabe mi estructura de **Gulp** y sin ningún framework de diseño
- Para webs de proyectos personales etc suelo usar **Jekyll**

Supongo que para mis necesidades como front actualmente no necesito mucho más. No he usado más que para un proyecto **Angular4** y he de decir que no me convencía **Typescript** por aquello de la curva de aprendizaje (no digo que sea ni malo ni bueno).

**Comment by juanmirod** [comment]
Muchas gracias por las respuestas, además hay mucha variedad :smiley:

Yo suelo trabajar con Angular y antes con AngujarJS, llevo un tiempo trabajando también con RxJS y con el ngStore, que es como Redux y la verdad es que me gusta porque ya conozco Angular y los observables permiten que sea todo más declarativo y funcional y el router de Angular es una maravilla, pero a la vez me molestan muchas cosas como la Inversión de dependencias, que todos sean clases y tenga que estar usando 'this' por todos lados, la complicación de los tests... 

@IgnaciodeNuevo Typescript merece la pena mucho, sobre todo si usas Code o algún editor con extensiones para typescript, las ayudas para navegar el código, refactorizar y la seguridad que te da el tipado automático son cubos de salud mental para el trabajo diario.

Tengo curiosidad por probar React o incluso alguno de los lenguajes funcionales para front como Elm o ClojureScript, ¿Alguno habéis probado alguno de ellos?
